---
- name:
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Find EC2 Facts
      ec2_instance_info:
        filters: 
          "tag:Name": prod
          "instance-state-name": running
      register: ec2_facts

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ item.public_ip_address }}" 
        port: 22 
        state: started
      loop: "{{ ec2_facts.instances }}"

    # - debug:
    #     msg: "{{ item.public_ip_address }}"
    #   with_items: "{{ ec2_facts.instances }}"

    - name: Create host group
      add_host: 
        hostname: "{{ item.public_ip_address }}"
        groupname: "prod"
      loop: "{{ ec2_facts.instances }}"

- name: Create Docker in AWS instance 
  hosts: prod
  become: yes
  gather_facts: no

  tasks:
    - name: Packages install
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: "3600"
      loop:
        - python3-pip
        - awscli
        - docker.io

    - name: Install docker python package
      pip:
        name: 
          - docker

    - name: Copy awscli credentials to instance
      copy:
        src: ~/.aws
        dest: ~/
        mode: "0644"
    
    - name: Do ECR login
      shell: "$(aws ecr get-login --no-include-email --region {{ aws_region }})"

    - name: Get Docker Repository Url for app
      shell: "aws ecr describe-repositories | awk '/repositoryUri/ && /{{ app_name }}/ { gsub(/\"|,/,\"\"); print $2 }'"
      register: repo_url

    - name: Run a "{{ app_name }}" Docker container
      docker_container:
        container_default_behavior: no_defaults
        name: "{{ app_name }}"
        image: "{{ repo_url.stdout }}"
        env:
            RED5_HOME: "/srv/red5-server"
        command: bash /srv/red5-server/red5.sh
        state: started
        ports:
            - "5080:5080"
            - "9999:9999"
            - "1935:1935"
        recreate: yes
